@baseUrl = http://localhost:8000/api/v1

# Регистрация покупателя
POST {{baseUrl}}/user/register
Content-Type: application/json

{
	"username": "gogivan",
	"first_name": "Gogi",
	"last_name": "Vangogi",
	"email": "gogivan@mail.ru",
	"password": "P4ssWord1",
	"company": "PopStar",
	"position": "manager"
}

###

# Авторизация
POST {{baseUrl}}/user/login
Content-Type: application/json

{
	"email": "test4dyplom@mail.ru",
	"password": "P4ssWord1"
}

###

# Подтверждение регистрации
POST {{baseUrl}}/user/register/confirm
Content-Type: application/json

{
	"email": "test4dyplom@mail.ru",
	"Token": "b95cb0df5296ecd3d8c906d98b602910b514"
}

###

# Сброс пароля
POST {{baseUrl}}/user/password_reset
Content-Type: application/json
Authorization: Token b540dd5bfb8a110fbe0fb1df9984f9394cf3a63d

{
	"email": "user1@user.com"
}

###

# Редактирование данных пользователя
POST {{baseUrl}}/user/details
Content-Type: application/json
Authorization: Token 2a940bcc2a0ed30b487394edf70ee0131b7712cf

{
	"email": "userONE@user.com"
}

###

# Контакты пользователя детально
GET {{baseUrl}}/user/details
Content-Type: application/json


###